// Autogenerated file
#include <array>
#include <map>
#include <QString>

inline constexpr uint armor_count() {return 676;}
#define _QSL(str) QStringLiteral(str)
using ArmorModeT = std::array<int, armor_count()>;
using ArmorNameT = std::array<QString, armor_count()>;
using ArmorTranslationsT = std::map<QString, ArmorNameT>;

extern const ArmorModeT armorMode;
extern const ArmorTranslationsT armorData;
